### ISSUE TITLE
Release for Linux

### ISSUE THREAD

**Issue by BrightDV** [Ranger-NF/Blackhole-Linux#1]
I looked around in the code, and I guess that starting from scratch with a new package is not preferable (or even doable within a reasonable time...).
Therefore, I am trying to use [just_audio_mpv](https://pub.dev/packages/just_audio_mpv) which uses [mpv_dart](https://pub.dev/packages/mpv_dart). However, the last package has not been active for over 1 year, so I added it inside the repo, and I am currently debugging it to understand what is wrong ;)

**Comment by FahadLive** [comment]
I did try using [just_audio_mpv](https://pub.dev/packages/just_audio_mpv) but there seems to be some kind of error within the library which stops it from playing the audio. Unfortunately, The error is not visible via debugging (I spend about 2 hours going through the rabbit hole of stack traces).

But if you do find the problem, please let me know! I will be more than happy to work on this project =)

**Comment by BrightDV** [comment]
What I saw is that mpv_dart wants to access properties from the player which are not set so it crashes
![image](https://github.com/Ranger-NF/Blackhole-Linux/assets/92821484/23703c84-2252-4658-bef8-50548d1f9733)

**Comment by BrightDV** [comment]
It seems that there is a problem inside just_audio_mpv or mpv_dart itself. I will open an issue on the first package to see it it can be resolved.

**Comment by FahadLive** [comment]
Yeah, Thats what I was expecting... Hope it get resolved.....

**Comment by BrightDV** [comment]
~~I just revert all my changes and the songs just played fine, but in the background with no way to stop it... 
The UI does not work yet, but it seems promising!~~
My bad, I wasn't using just_audio...

**Comment by BrightDV** [comment]
[Capture vidéo du 17-06-2023 18:38:39.webm](https://github.com/Ranger-NF/Blackhole-Linux/assets/92821484/b2b31c93-4172-4094-853a-76941ab255e7)

*(there is sound)*

I'm just too happy 🥳 It was only **one property* which set the start time that was causing the crash... I will open a PR with the fix!

**Comment by FahadLive** [comment]
It works for the most part (ignoring the errors printed on to console), I might try and pull the latest changes as the next step. Btw, Nice work mate =)

**Comment by BrightDV** [comment]
I just did a Debian build and it works flawlessy!
Also, you can add to the conf file a build number to the Version and a Homepage.
```yaml
flutter_app: 
  command: blackhole
  arch: x64
  parent: /usr/local/lib

control:
  Package: BlackHole
  Version: 0.1.0+1
  Architecture: amd64
  Essential: no
  Priority: optional
  Depends:
  Maintainer:
  Description: An Open-Source Music Player App for all your needs!
  Homepage: https://github.com/Ranger-NF/Blackhole-Linux

```

**Comment by FahadLive** [comment]
I have changed all those things you mentioned and added our names to the maintainers field, but I have not been able to add icon to the .deb package

Also, check out this issue to remove the warning shown upon installing the package: 
[Stackoverflow solution](https://stackoverflow.com/questions/75300696/debian-package-management-warning-and-error-message) `EDIT: It shows an error when installed via github`

**Comment by BrightDV** [comment]
> I have not been able to add icon to the .deb package

Do you mean the icon displayed in the file explorer? Because I can see the icon in the dock.

> Also, check out this issue to remove the warning shown upon installing the package:
[Stackoverflow solution](https://stackoverflow.com/questions/75300696/debian-package-management-warning-and-error-message) EDIT: It shows an error when installed via github

I just found that it is because you have set *two* maintainers whereas there should be one.
![image](https://github.com/Ranger-NF/Blackhole-Linux/assets/92821484/16252585-5be5-44ef-abf4-9e1f1634d3b3)
So there is a List instead of the String expected.

[I searched a bit and there can't be two maintainers, the workaround is: one Maintainer and one Uploader (which means co-maintainer).](https://www.debian.org/doc/debian-policy/ch-controlfields.html#maintainer)

![image](https://github.com/Ranger-NF/Blackhole-Linux/assets/92821484/e0741bc2-20d6-4d7c-b4df-98aec800b08d)

I updated the file, and also removed GitHub URLs as there should be only email addresses (it seems to be a bit old, so it might break otherwise ;).
```yaml
flutter_app: 
  command: blackhole
  arch: x64
  parent: /usr/local/lib
  nonInteractive: true

control:
  Package: BlackHole
  Version: 0.1.0+3
  Architecture: amd64
  Essential: no
  Priority: optional
  Maintainer: Ranger
  Uploaders: BrightDV
  Description: An Open-Source Music Player App for all your needs!
  Homepage: https://github.com/Ranger-NF/Blackhole-Linux
```
I tested with this conffile and it works fine.
